## YAML Template.
---
spring:
  application:
    name: "@project.artifactId@"

  data:
    rest:
      base-path: /api


  flyway:
    enabled: true
    locations: classpath:db/migrations/{vendor}


  jpa:
    generate-ddl: false
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

info:
  application:
    name: "@project.artifactId@"
    version: "@project.version@"
    description: "@project.description@"
    build-date: "@build.date@"


