# Datasource Config for profile mysql
---
spring:
  datasource:
    name: mysql-cdr
    url: jdbc:mysql://outerspace/cdrdb
    username: cdrdb
    password: cdrpass
    driver-class-name: com.mysql.jdbc.Driver
